Repository labs14-stampd/frontend, pull requests merged in 2019-08, with the labels that each got.

#33 Add Google Analytics to Production Site
  client/public/index.html
  client/yarn.lock
Labels: enhancement

#34 Make Draft Landing Page Styles and Update General Styles
  client/assets/dashboardExample.png
  client/assets/issuecredential.png
  client/assets/schooldashboard.png
  client/assets/stampd_landing.png
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/Dashboard/index.jsx
  client/src/components/Landing/index.jsx
  client/src/components/Layout/Footer/index.jsx
  client/src/components/Layout/NavBar/index.jsx
  client/src/images/stampdbackground.svg
  client/src/styles/Global.js
  client/src/styles/Reset.js
  client/src/styles/index.js
  client/src/styles/themes.js
Labels: enhancement

#39 Merge Styles Branch into Master for Deployment of Current Work
  client/src/components/Dashboard/CredentialsForm/index.jsx
  client/src/components/Dashboard/Onboard/SchoolDetailsForm.jsx
  client/src/components/Dashboard/Onboard/index.jsx
  client/src/components/Dashboard/index.jsx
  client/src/components/Field.jsx
  client/src/components/Landing/index.jsx
  client/src/components/Layout/Footer.jsx
  client/src/components/Layout/NavBar.jsx
  client/src/components/Layout/index.jsx
  client/src/images/certEmblem.png
  client/src/store/reducers/globalReducer.js
  client/src/styles/Global.js
  client/src/styles/themes.js
Labels: enhancement

#40 Fix Linting Issues and Make Landing Page Mobile Responsive
  client/src/components/Landing/index.jsx
  client/src/components/Layout/index.jsx
  client/src/styles/index.js
  client/src/styles/themes.js
Labels: enhancement

#45 Adds Additional Styling and Updates to README.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  assets/issue-cert-screenshot.png
  assets/landing-screenshot.png
  assets/readme-header.png
  client/assets/bcon_profile.png
  client/assets/cjbt_profile1.png
  client/assets/nwthomas_profile.JPG
Labels: documentation

#56 Implement Routing and Functionality on the Navbar Menu Tray
  client/src/App.jsx
  client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
  client/src/components/Layout/MenuLayer.jsx
  client/src/components/Layout/NavBar.jsx
  client/src/components/Layout/index.jsx
  client/src/styles/themes.js
Labels: enhancement

#69 Dashboard Styling Updates and Tweaks
  assets/dashboardExample.png
  assets/issuecredential.png
  assets/schooldashboard.png
  assets/stampd_landing.png
  client/public/android-icon-144x144.png
  client/public/android-icon-192x192.png
  client/public/android-icon-36x36.png
  client/public/android-icon-48x48.png
  client/public/android-icon-72x72.png
  client/public/android-icon-96x96.png
  client/public/apple-icon-114x114.png
  client/public/apple-icon-120x120.png
  client/public/apple-icon-144x144.png
  client/public/apple-icon-152x152.png
  client/public/apple-icon-180x180.png
  client/public/apple-icon-57x57.png
  client/public/apple-icon-60x60.png
  client/public/apple-icon-72x72.png
  client/public/apple-icon-76x76.png
  client/public/apple-icon-precomposed.png
  client/public/apple-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/ms-icon-144x144.png
  client/public/ms-icon-150x150.png
  client/public/ms-icon-310x310.png
  client/public/ms-icon-70x70.png
  client/src/auth/authWrapper.jsx
  client/src/components/Dashboard/Card/CredCard.jsx
  client/src/components/Dashboard/Card/CredCardDeleteBtn.jsx
  client/src/components/Dashboard/Card/CredCardViewBtn.jsx
  client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
  client/src/components/Layout/NavBar.jsx
  client/src/images/s_violet.png
  client/src/images/s_violet.svg
  client/src/images/s_white.svg
  client/src/images/stampd_full_violet.png
  client/src/images/stampd_full_violet.svg
  client/src/images/stampd_full_white.png
  client/src/images/stampd_full_white.svg
Labels: enhancement

#50 Update README with Testing and Project Management section content
  README.md
Labels: documentation

#70 Fix Left/Right Cred Card Hover Bug
  client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
  client/src/components/Dashboard/SchoolDashboard/index.jsx
Labels: bug, enhancement

#72 Create Settings Page and Route
  client/src/App.jsx
  client/src/components/Dashboard/Dashboard/SchoolDashboard.jsx
  client/src/components/Dashboard/Dashboard/StudentDashboard.jsx
  client/src/components/Dashboard/Dashboard/index.jsx
  client/src/components/Dashboard/Dashboard/queries.js
  client/src/components/Dashboard/Onboard/SchoolDetailsForm.jsx
  client/src/components/Dashboard/Onboard/StudentDetailsForm.jsx
  client/src/components/Dashboard/Onboard/queries.js
  client/src/components/Layout/MenuLayer.jsx
  client/src/components/Settings/StudentSettings/DetailsSettings.jsx
  client/src/components/Settings/StudentSettings/EmailSettings.jsx
  client/src/components/Settings/StudentSettings/StudentSettings.jsx
  client/src/components/Settings/index.jsx
  client/src/components/Settings/queries.js
  client/src/store/constants.js
  client/src/store/reducers/globalReducer.js
  client/src/store/reducers/schoolReducer.js
  client/src/store/reducers/studentReducer.js
  client/src/styles/themes.js
Labels: enhancement

#75 Make bug fixes for rendering the dashboard data
  client/src/App.jsx
  client/src/components/Dashboard/Dashboard/StudentDashboard.jsx
  client/src/components/Dashboard/Dashboard/index.jsx
  client/src/store/reducers/schoolReducer.js
Labels: bug

#77 Add Additional Tests to Client
  client/src/__testHelpers__/renderWithRouter/renderWithRouterAndProviders.jsx
  client/src/__testHelpers__/rendererWithRouter/rendererWithRouterAndProviders.jsx
  client/src/__tests__/Dashboard.test.js
  client/src/__tests__/ErrorPage.test.js
  client/src/__tests__/Footer.test.js
  client/src/__tests__/Landing.test.js
  client/src/__tests__/Layout.test.js
  client/src/__tests__/Loading.test.js
  client/src/__tests__/MenuLayer.test.js
  client/src/__tests__/NavBar.test.js
  client/src/__tests__/SchoolDashboard.test.js
  client/src/__tests__/StudentDashboard.test.js
  client/src/__tests__/__snapshots__/CredCard.test.js.snap
  client/src/__tests__/__snapshots__/Dashboard.test.js.snap
  client/src/__tests__/__snapshots__/ErrorPage.test.js.snap
  client/src/__tests__/__snapshots__/Footer.test.js.snap
  client/src/__tests__/__snapshots__/Landing.test.js.snap
  client/src/__tests__/__snapshots__/Layout.test.js.snap
  client/src/__tests__/__snapshots__/Loading.test.js.snap
  client/src/__tests__/__snapshots__/NavBar.test.js.snap
  client/src/__tests__/__snapshots__/SchoolDashboard.test.js.snap
  client/src/__tests__/__snapshots__/StudentDashboard.test.js.snap
  client/src/auth/__mocks__/authWrapper.jsx
  client/src/components/Layout/Loading.jsx
  client/src/components/Layout/NavBar.jsx
  client/src/store/reducers/__mocks__/globalReducer.js
  client/src/store/reducers/__mocks__/schoolReducer.js
  client/src/store/reducers/__mocks__/studentReducer.js
Labels: enhancement

#78 Finish Updates for bug/addEmail Branch
  client/src/components/Settings/StudentSettings/EmailContainer.jsx
  client/src/components/Settings/StudentSettings/EmailSettings.jsx
  client/src/components/Settings/queries.js
  client/src/store/reducers/studentReducer.js
Labels: bug

#88 Removed userId from emailList query
  client/src/components/Settings/queries.js
Labels: bug

#98 Add new header tags to index.html
  client/public/index.html
Labels: bug

#101 Bugfix/hamburgerf
  client/src/auth/authWrapper.jsx
Labels: bug
